
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.beezlabs.com
  resources:
  - testoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.beezlabs.com
  resources:
  - testoperators/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.beezlabs.com
  resources:
  - testoperators/status
  verbs:
  - get
  - patch
  - update
