# permissions for end users to view testoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testoperator-viewer-role
rules:
- apiGroups:
  - webapp.beezlabs.com
  resources:
  - testoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.beezlabs.com
  resources:
  - testoperators/status
  verbs:
  - get
